
server:
  port: 8013
spring:

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-247-118-139.eu-west-1.compute.amazonaws.com:5432/d82m3g8sh7eak2
    username: etjjgzbojhywta
    password: 12e69d28bccff4ca1d0886fd6a2eec2b74780b4768f53da284b6e8b29c5b3ce3


  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect